name: app ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'adopt'
            - name: run postgresql
              run: make postgres
            - name: Make mvnw executable
              run: chmod +x ./mvnw
            - name: run migrations
              run: make migrate
            - name: build app
              run: make build
            - name: Run Tests
              run: make test